server:
  port: 8989

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  mvc:
#    static-path-pattern: /aab/**
#  web:
#    resources:
#      static-locations: [classpath:/abc/]
